import {books,palette,pageNames} from './data.js';
import {svgArt,artwork} from './art.js';
const $=s=>document.querySelector(s), main=$('#main');
let wishes=read('homepilato-wishes',[]), book=books[0], page=0, selected=palette[0][1], mode='color', history=[], timers=[], opener=null;
let colors=read('homepilato-coloring',{}), filter='All books';
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{toast('Storage unavailable. You can still save your artwork.');}}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=()=>`${book.id}:${page}`;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
function cover(b,cls=''){return `<div class="book-cover ${cls}" style="--cover:${b.color};--cover-ink:${b.ink}"><span class="cover-brand">HOME PILATO STUDIO</span><strong>${b.title}</strong><span class="cover-subtitle">${b.subtitle}</span>${svgArt(b.previewPages[0],{colored:true,uid:`cover-${b.id}-${cls}`})}<span class="cover-footer">${b.category==='How to Draw'?'STEP-BY-STEP DRAWING':'A LITTLE BOOK OF COLOR & JOY'}</span></div>`;}
function card(b){return `<article class="book-card"><button class="cover-button" data-preview="${b.id}" aria-label="Preview ${b.title}">${cover(b)}<span class="cover-cta">Take a peek inside ↗</span></button><div class="book-meta"><span>${b.category}</span><button class="wish" data-wish="${b.id}" aria-label="${wishes.includes(b.id)?'Remove':'Add'} ${b.title} ${wishes.includes(b.id)?'from':'to'} wishlist" aria-pressed="${wishes.includes(b.id)}">${wishes.includes(b.id)?'♥':'♡'}</button></div><a class="book-title" href="#/books/${b.id}">${b.title} ↗</a><p>Ages ${b.ageRange} · ${b.pageCount} creative pages</p><span class="demo-label">Demo edition</span></article>`;}
function hero(){return `<section class="hero"><div class="hero-ribbon" aria-hidden="true"></div><div class="hero-copy"><span class="eyebrow">FOR LITTLE ARTISTS & BIG IMAGINATIONS</span><h1>Color outside<br>the <em>ordinary.</em></h1><p>Open a book. Find your happy colors.<br>Make a little magic, one page at a time.</p><div class="hero-ctas"><a class="button pink" href="#/books">Find your next adventure <span>↗</span></a><button class="text-link" data-preview="cozy-critters">Try a little coloring <span>↗</span></button></div><span class="hero-note">Less screen time. More “look what I made!”</span></div><div class="hero-books"><button class="hero-book hero-book-back" data-preview="little-dreamers" aria-label="Preview Little Dreamers">${cover(books[1])}</button><button class="hero-book hero-book-front" data-preview="cozy-critters" aria-label="Preview Cozy Critters">${cover(books[0])}</button><span class="round-sticker">OPEN ME.<br>COLOR ME.<br><b>LOVE ME. ↗</b></span><span class="hand-note">Yes, you can<br>color inside! ⤴</span></div><div class="hero-bottom"><span>HAPPINESS, BETWEEN TWO COVERS.</span><a href="#collection">SCROLL TO EXPLORE ↓</a></div></section>`;}
function collection(){return `<section class="collection section" id="collection"><div class="section-heading"><div><span class="eyebrow">YOUR NEXT HAPPY PLACE</span><h2>Small books.<br>Big possibilities.</h2></div><p>Meet your next “just one more page.”<br>Tap a cover to see where it takes you.</p></div><div class="filters" role="group" aria-label="Book categories">${['All books','Cute Animals','Fantasy','Ocean','How to Draw'].map(x=>`<button data-filter="${x}" aria-pressed="${filter===x}">${x}</button>`).join('')}</div><div class="book-grid" id="book-grid">${books.filter(b=>filter==='All books'||b.category===filter).map(card).join('')}</div></section>`;}
function steps(){return `<section class="how-it-works section"><span class="eyebrow">NO RULES. JUST A LITTLE WONDER.</span><div class="section-heading"><h2>From blank<br>to <em>brilliant.</em></h2><button class="button dark" data-preview="cozy-critters">Make some magic <span>↗</span></button></div><div class="steps">${[['Pick your happy place.','Animals, daydreams, or things that go. Find a book that feels like you.'],['Add a little you.','Try a page right here. Pick a color, tap a space, and watch it bloom.'],['Take the magic offline.','Bring your favorite book to the table. Just add pencils and imagination.']].map((s,i)=>`<article><div class="step-art">${svgArt('cat',{colored:i>0,stage:i===1?6:99,uid:'step-'+i})}<span class="step-number">0${i+1}</span></div><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('')}</div></section>`;}
function benefits(){return `<section class="benefits section"><span class="eyebrow">GOOD THINGS GROW ON PAPER</span><h2>Made for their imagination.<br>And your peace of mind.</h2><div class="benefit-grid">${[['✳','Screen-free moments','A little space to unplug and make something.'],['✎','Creative confidence','Small steps, surprising discoveries, proud little smiles.'],['❋','Little hands, big ideas','Roomy shapes that invite experimenting with color.'],['♡','Give a little joy','An everyday adventure, wrapped up in a book.']].map(b=>`<article><span>${b[0]}</span><h3>${b[1]}</h3><p>${b[2]}</p></article>`).join('')}</div></section>`;}
function gallery(){return `<section class="gallery section"><div class="section-heading"><h2>A page.<br>A thousand possibilities.</h2><p>Same little drawing. A whole new feeling.<br>Studio color studies — now it’s your turn.</p></div><div class="gallery-grid">${['cat','bunny','flower','mushroom'].map((x,i)=>`<button data-preview="${books[i].id}" aria-label="Try coloring ${books[i].title}" style="--paper:${['#f4c2d5','#c6bce5','#c3d4ae','#efbe83'][i]}">${svgArt(x,{colored:true,uid:'gallery-'+i})}<span>${['A peachy afternoon','Lilac daydreams','Freshly picked','A tiny escape'][i]} ↗</span></button>`).join('')}</div></section>`;}
function freeSection(){return `<section class="free-section section"><div><span class="eyebrow">A LITTLE SOMETHING, JUST BECAUSE</span><h2>Free coloring pages?<br><em>Yes, please.</em></h2><p>Your next creative afternoon starts here.<br>Download an original sample and make it yours.</p><a class="button dark" href="#/activities">Get your free pages <span>↓</span></a></div><div class="free-art">${svgArt('bunny',{uid:'free-bunny'})}<span>PRINT.<br>COLOR.<br>REPEAT.</span></div></section>`;}
function faq(){return `<section class="faq section"><h2>A little curious?</h2><div>${[['Can I try a page before choosing a book?','Of course. Tap any book cover to browse six sample pages, watch colors appear, or try coloring them yourself.'],['Are these the final book covers and interiors?','These demo editions show how the studio experience works. Final covers, specifications, prices, and Amazon listings will be added when the real catalog is connected.'],['Can I save my coloring?','Yes! Your work is stored on this device, and Save artwork downloads an SVG that can be opened in a browser or printed.'],['Do I need an account?','No account is needed to preview, color, or download the free demo pages.']].map(([q,a])=>`<details><summary>${q}<span>+</span></summary><p>${a}</p></details>`).join('')}</div></section>`;}
function detail(b){return `<section class="product section"><a class="text-link" href="#/books">← All books</a><div class="product-grid"><div class="product-cover"><button class="cover-button" data-preview="${b.id}" aria-label="Preview ${b.title}">${cover(b)}</button></div><div class="product-copy"><span class="eyebrow">${b.category.toUpperCase()} / DEMO EDITION</span><h1>${b.title}</h1><p>${b.description}</p><dl><div><dt>Made for</dt><dd>Ages ${b.ageRange}</dd></div><div><dt>Inside</dt><dd>${b.pageCount} creative pages</dd></div><div><dt>Size</dt><dd>${b.bookSize}</dd></div><div><dt>Printed</dt><dd>Single-sided pages</dd></div></dl><div class="product-actions"><button class="button pink" data-preview="${b.id}">Look inside & color <span>↗</span></button>${b.amazonUrl?`<a class="button dark" href="${escape(b.amazonUrl)}" target="_blank" rel="noopener noreferrer">Buy on Amazon ${b.price?'· $'+b.price:''} ↗</a>`:'<p class="availability">Amazon purchase link coming soon.</p>'}</div><button class="text-link" data-wish="${b.id}">${wishes.includes(b.id)?'♥ Saved to':'♡ Add to'} wishlist</button></div></div></section><section class="inside section"><div class="section-heading"><h2>A little look inside.</h2><p>Six tiny adventures.<br>Pick one and make it your own.</p></div><div class="inside-gallery">${b.previewPages.map((p,i)=>`<button data-preview="${b.id}" data-page="${i}" aria-label="Preview ${pageNames[p]}">${svgArt(p,{colored:i%2===1,uid:'inside-'+i})}<span>0${i+1} / ${pageNames[p]} ↗</span></button>`).join('')}</div></section>${freeSection()}`;}
function activities(){return `<section class="section activity-page"><span class="eyebrow">PRINT A LITTLE HAPPINESS</span><h1>Off-screen.<br>On paper.</h1><p>Original demo printables, free for personal use.<br>Download, open in your browser, and print.</p><div class="book-grid">${['cat','bunny','flower','car'].map(x=>`<article><div class="printable">${svgArt(x,{uid:'print-'+x})}</div><h3>${pageNames[x]}</h3><button class="button dark" data-print="${x}">Download page ↓</button></article>`).join('')}</div><div class="draw-lesson"><h2>Draw a little car.</h2><p>Start with a rounded rectangle. Add a roof, two wheels, and windows. Finish with your favorite colors.</p><div class="draw-steps">${[1,2,3].map((n)=>`<div><svg viewBox="0 0 400 230" role="img" aria-label="Car drawing step ${n}"><g fill="none" stroke="#302d33" stroke-width="4"><rect x="70" y="110" width="260" height="65" rx="20"/>${n>=2?'<path d="M100 110L135 50H263L300 110Z"/><circle cx="130" cy="177" r="28" fill="white"/><circle cx="268" cy="177" r="28" fill="white"/>':''}${n===3?'<path d="M144 62H190V100H122Z M206 62H254L278 100H206Z M173 151Q200 165 226 151"/>':''}</g></svg><span>0${n} — ${['A simple shape','A roof & wheels','Make it yours'][n-1]}</span></div>`).join('')}</div></div></section>`;}
function render(){closePreview();let route=decodeURIComponent(location.hash.replace(/^#\/?/,'')||'');$('#navigation').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');if(route.startsWith('books/')){const b=books.find(x=>x.id===route.split('/')[1]);main.innerHTML=b?detail(b):'<section class="section"><h1>Book not found.</h1><a href="#/books">Back to all books</a></section>';document.title=b?`${b.title} — Homepilato Studio`:'Book not found — Homepilato';}else{document.title='Homepilato Studio — Color outside the ordinary';if(route==='books'||route==='how-to-draw'){filter=route==='how-to-draw'?'How to Draw':'All books';main.innerHTML=collection()+freeSection();}else if(route==='activities'){main.innerHTML=activities();}else if(route==='wishlist'){main.innerHTML=`<section class="section"><span class="eyebrow">YOUR LITTLE COLLECTION</span><h1>Saved for a<br>colorful day.</h1><div class="book-grid">${books.filter(b=>wishes.includes(b.id)).map(card).join('')||'<p>No saved books yet. Tap a heart to keep a favorite here.</p>'}</div><a class="text-link" href="#/books">Explore all books ↗</a></section>`;}else if(route==='about'){main.innerHTML=`<section class="about section"><span class="eyebrow">HELLO FROM HOME PILATO</span><h1>Big wonder.<br>Little pages.</h1><p>Homepilato Studio creates coloring and step-by-step drawing books for curious minds. We believe a few simple shapes, a handful of colors, and a little time can become something wonderful.</p><p>This preview collection brings that idea to life. Explore the artwork, experiment with colors, and take an original printable to your own creative table.</p><a class="button pink" href="#/books">Find your happy place ↗</a></section>${benefits()}`;}else if(route==='privacy'){main.innerHTML='<section class="section about"><h1>Your privacy.</h1><p>This demo does not collect email addresses, process payments, or use analytics. Wishlist and coloring data stay in your browser’s local storage. You can remove them by clearing this site’s browser data.</p><p>Downloads are generated in your browser. Future external purchase links will open Amazon, where Amazon’s privacy policy applies.</p></section>';}else{main.innerHTML=hero()+`<div class="marquee" aria-hidden="true"><span>COLOR YOUR HAPPY ✳ LITTLE PAGES, BIG JOY ✳ MADE FOR IMAGINATION ✳ COLOR YOUR HAPPY ✳</span></div>`+collection()+steps()+benefits()+gallery()+freeSection()+faq();}}
$('#wish-count').textContent=wishes.length;window.scrollTo(0,0);}
function stopDemo(){timers.forEach(clearTimeout);timers=[];$('#auto-color').textContent='✦ Watch it color';}
function renderPage(){stopDemo();history=[];mode='color';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));$('#comparison-control').hidden=true;$('#palette').hidden=false;$('#preview-title').textContent=book.title;$('#guide-art').innerHTML=svgArt(book.previewPages[page],{colored:true,uid:'guide'});$('#page-name').textContent=pageNames[book.previewPages[page]];$('#page-counter').textContent=String(page+1).padStart(2,'0');$('#page-status').textContent=`${page+1} / ${book.previewPages.length} sample pages`;$('#previous-page').disabled=page===0;$('#next-page').disabled=page===book.previewPages.length-1;$('#preview-detail').href=`#/books/${book.id}`;drawCanvas();$('#undo').disabled=true;}
function drawCanvas(){const c=colors[key()]||{};$('#coloring-canvas').innerHTML=svgArt(book.previewPages[page],{colors:c,interactive:mode==='color',uid:'canvas',compare:mode==='compare'?Number($('#comparison').value):null});}
function openPreview(id,start=0){book=books.find(b=>b.id===id)||books[0];page=Math.min(Math.max(start,0),book.previewPages.length-1);opener=document.activeElement;renderPage();$('#preview').showModal();document.body.classList.add('modal-open');if(!colors[key()]&&!matchMedia('(prefers-reduced-motion: reduce)').matches)timers.push(setTimeout(()=>demo(),1000));}
function closePreview(){if(!$('#preview').open)return;stopDemo();$('#preview').close();document.body.classList.remove('modal-open');opener?.focus();}
function paint(id,color=selected){if(mode!=='color')return;stopDemo();const k=key();history.push({...colors[k]});colors[k]={...colors[k],[id]:color};save('homepilato-coloring',colors);const region=$(`[data-region="${id}"]`);if(region){region.setAttribute('fill',color);region.classList.remove('paint-pop');void region.getBoundingClientRect();region.classList.add('paint-pop');}$('#undo').disabled=false;$('#color-announcement').textContent=`Colored ${id.replaceAll('-',' ')}`;}
function demo(){stopDemo();mode='color';$('#comparison-control').hidden=true;$('#palette').hidden=false;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));history.push({...colors[key()]});colors[key()]={};drawCanvas();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;$('#auto-color').textContent='✦ Coloring…';artwork(book.previewPages[page]).regions.forEach((r,i)=>timers.push(setTimeout(()=>{colors[key()][r.id]=r.color;const el=$(`[data-region="${r.id}"]`);el?.setAttribute('fill',r.color);el?.classList.add('paint-pop');if(i===artwork(book.previewPages[page]).regions.length-1){save('homepilato-coloring',colors);$('#auto-color').textContent='✦ Replay colors';$('#undo').disabled=false;}},reduced?0:i*180)));}
function download(svg,name){const blob=new Blob([svg],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name+'.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#palette').innerHTML=palette.map(([name,hex],i)=>`<button style="--swatch:${hex}" data-color="${hex}" aria-label="${name}" title="${name}" aria-pressed="${i===0}"></button>`).join('');
document.addEventListener('click',e=>{const t=e.target.closest('[data-preview],[data-wish],[data-filter],[data-print]');if(!t)return;if(t.dataset.preview){openPreview(t.dataset.preview,Number(t.dataset.page||0));}else if(t.dataset.wish){const id=t.dataset.wish;wishes=wishes.includes(id)?wishes.filter(x=>x!==id):[...wishes,id];save('homepilato-wishes',wishes);$('#wish-count').textContent=wishes.length;const saved=wishes.includes(id);document.querySelectorAll(`[data-wish="${id}"]`).forEach(b=>{b.setAttribute('aria-pressed',saved);b.innerHTML=b.classList.contains('wish')?(saved?'♥':'♡'):(saved?'♥ Saved to wishlist':'♡ Add to wishlist');b.setAttribute('aria-label',`${saved?'Remove':'Add'} ${books.find(x=>x.id===id).title} ${saved?'from':'to'} wishlist`);});if(location.hash==='#/wishlist')render();toast(saved?'Saved to your wishlist.':'Removed from your wishlist.');}else if(t.dataset.filter){filter=t.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.filter===filter));$('#book-grid').innerHTML=books.filter(b=>filter==='All books'||b.category===filter).map(card).join('');}else if(t.dataset.print){download(svgArt(t.dataset.print),`homepilato-${t.dataset.print}-printable`);}});
$('#palette').addEventListener('click',e=>{const t=e.target.closest('[data-color]');if(!t)return;stopDemo();selected=t.dataset.color;$('#palette').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b===t));});
$('#coloring-canvas').addEventListener('click',e=>{const r=e.target.closest('[data-region]');if(r)paint(r.dataset.region);});
$('#coloring-canvas').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.region){e.preventDefault();paint(e.target.dataset.region);}});
$('#undo').onclick=()=>{stopDemo();if(!history.length)return;colors[key()]=history.pop();save('homepilato-coloring',colors);drawCanvas();$('#undo').disabled=!history.length;};
$('#reset').onclick=()=>{stopDemo();history.push({...colors[key()]});colors[key()]={};save('homepilato-coloring',colors);drawCanvas();$('#undo').disabled=false;};
$('#auto-color').onclick=demo;
$('#download-art').onclick=()=>download(svgArt(book.previewPages[page],{colors:colors[key()]||{},uid:'saved'}),`homepilato-${book.id}-${page+1}`);
$('#close-preview').onclick=closePreview;$('#preview').addEventListener('cancel',e=>{e.preventDefault();closePreview();});$('#preview').addEventListener('click',e=>{if(e.target===$('#preview'))closePreview();});$('#preview-detail').onclick=closePreview;
$('#previous-page').onclick=()=>{if(page>0){page--;renderPage();}};$('#next-page').onclick=()=>{if(page<book.previewPages.length-1){page++;renderPage();}};
let touchStart=null;$('.book-workspace').addEventListener('touchstart',e=>{touchStart={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY};},{passive:true});$('.book-workspace').addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>70&&Math.abs(dy)<45){if(dx<0)$('#next-page').click();else $('#previous-page').click();}touchStart=null;},{passive:true});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{stopDemo();mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#comparison-control').hidden=mode!=='compare';$('#palette').hidden=mode==='compare';drawCanvas();});$('#comparison').oninput=drawCanvas;
$('#menu-toggle').onclick=()=>{$('#navigation').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',$('#navigation').classList.contains('open'));};$('#wishlist-open').onclick=()=>location.hash='/wishlist';
function search(){const query=$('#search-input').value.toLowerCase().trim();const found=books.filter(b=>(b.title+' '+b.category).toLowerCase().includes(query));$('#search-results').innerHTML=found.map(b=>`<a href="#/books/${b.id}"><span style="background:${b.color}">${svgArt(b.previewPages[0],{colored:true,uid:'search-'+b.id})}</span><div><strong>${b.title}</strong><p>${b.category} · Ages ${b.ageRange}</p></div>↗</a>`).join('')||'<p>No books found. Try “animals” or “ocean”.</p>';}
$('#search-open').onclick=()=>{$('#search-dialog').showModal();search();$('#search-input').focus();};$('#search-close').onclick=()=>$('#search-dialog').close();$('#search-input').oninput=search;$('#search-results').onclick=e=>{if(e.target.closest('a'))$('#search-dialog').close();};
$('#year').textContent=new Date().getFullYear();window.addEventListener('hashchange',()=>{if(location.hash==='#collection'){$('#collection')?.scrollIntoView();return;}render();});render();
