/** Original choreography, based on observed reference behavior. No reference-site source is bundled. */
export const motionSettings=Object.freeze({heroCycle:5,scrollDuration:1.05,scrub:.65});
export const clamp=(x,a=0,b=1)=>Math.min(b,Math.max(a,x));
export function carouselState(left,width,total){const max=Math.max(0,total-width);return {max,previous:left>2,next:left<max-2,progress:max?clamp(left/max):0};}
let cleanup=[],context=null,lenis=null,g=null,st=null,mountId=0;
const listen=(el,type,fn,options)=>{el.addEventListener(type,fn,options);cleanup.push(()=>el.removeEventListener(type,fn,options));};
export function lockMotion(locked){if(locked)lenis?.stop();else lenis?.start();}
export function unmountMotion(){mountId++;if(g){const root=document.querySelector('#main');if(root)g.killTweensOf([...root.querySelectorAll('*')]);}cleanup.splice(0).forEach(fn=>fn());context?.revert();context=null;lenis?.destroy();lenis=null;document.documentElement.classList.remove('motion-ready');}
export function refreshMotion(){st?.refresh();}
function words(el){const nodes=[];const walk=node=>{for(const child of [...node.childNodes]){if(child.nodeType===3)nodes.push(child);else if(child.nodeType===1)walk(child);}};walk(el);el.setAttribute('aria-label',el.innerHTML.replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]*>/g,''));for(const node of nodes){const fragment=document.createDocumentFragment();node.textContent.split(/(\s+)/).forEach(word=>{if(!word.trim())fragment.append(document.createTextNode(word));else{const span=document.createElement('span');span.className='motion-word';span.setAttribute('aria-hidden','true');span.textContent=word;fragment.append(span);}});node.replaceWith(fragment);}return [...el.querySelectorAll('.motion-word')];}
function initCarousel(root,reduced){root.querySelectorAll('.book-rail').forEach(rail=>{const container=rail.closest('.book-showcase'),prev=container.querySelector('[data-carousel-prev]'),next=container.querySelector('[data-carousel-next]'),cards=[...rail.querySelectorAll('.shelf-card')];let down=null,moved=false,tween=null,settle;
const update=()=>{const state=carouselState(rail.scrollLeft,rail.clientWidth,rail.scrollWidth);prev.disabled=!state.previous;next.disabled=!state.next;container.querySelector('.carousel-position').textContent=`${String(Math.min(cards.length,Math.round(state.progress*(cards.length-1))+1)).padStart(2,'0')} — ${String(cards.length).padStart(2,'0')}`;};
const move=direction=>{const step=(cards[0]?.getBoundingClientRect().width||280)+36;const dest=clamp(rail.scrollLeft+step*direction,0,Math.max(0,rail.scrollWidth-rail.clientWidth));tween?.kill();if(g&&!reduced)tween=g.to(rail,{scrollLeft:dest,duration:.65,ease:'power3.out',onUpdate:update});else{rail.scrollLeft=dest;update();}};
listen(prev,'click',()=>move(-1));listen(next,'click',()=>move(1));listen(rail,'scroll',()=>{update();if(!g||reduced)return;g.to(cards,{rotationZ:clamp((rail.scrollLeft-(rail._lastLeft??rail.scrollLeft))*.14,-7,7),duration:.2,overwrite:true});rail._lastLeft=rail.scrollLeft;clearTimeout(settle);settle=setTimeout(()=>g.to(cards,{rotationZ:0,duration:.7,ease:'elastic.out(1,0.65)',overwrite:true}),80);},{passive:true});
listen(rail,'keydown',e=>{if(e.target!==rail)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1);}});
listen(rail,'pointerdown',e=>{if(e.pointerType==='touch'||e.button!==0)return;tween?.kill();moved=false;down={x:e.clientX,left:rail.scrollLeft};});
listen(window,'pointermove',e=>{if(!down)return;const delta=e.clientX-down.x;if(Math.abs(delta)>7){moved=true;rail.classList.add('dragging');rail.scrollLeft=down.left-delta;e.preventDefault();}});
const release=()=>{down=null;rail.classList.remove('dragging');};listen(window,'pointerup',release);listen(window,'pointercancel',release);
listen(rail,'click',e=>{if(moved){e.preventDefault();e.stopImmediatePropagation();moved=false;}},true);listen(rail,'dragstart',e=>e.preventDefault());listen(window,'resize',update);cleanup.push(()=>{clearTimeout(settle);tween?.kill();});update();});}
function buttonLetters(root){root.querySelectorAll('.split-button').forEach(button=>{const label=button.querySelector('.button-label');if(!label)return;const title=label.textContent;button.setAttribute('aria-label',title);label.setAttribute('aria-hidden','true');label.replaceChildren(...Array.from(title,c=>{const span=document.createElement('span');span.className='button-letter';span.textContent=c===' '?'\u00a0':c;return span;}));const animate=()=>{const chars=[...label.children];g.killTweensOf(chars);g.fromTo(chars,{y:0,scaleY:1,rotation:0},{keyframes:[{y:7,scaleY:.45,rotation:14,duration:.13},{y:0,scaleY:1,rotation:0,duration:.55,ease:'elastic.out(1,0.4)'}],stagger:.014,overwrite:true});};listen(button,'pointerenter',animate);listen(button,'focus',animate);cleanup.push(()=>label.textContent=title);});}
export function mountMotion(){const root=document.querySelector('#main');if(!root)return;g=window.gsap;st=window.ScrollTrigger;const preference=matchMedia('(prefers-reduced-motion: reduce)');const reduced=preference.matches;const change=()=>{unmountMotion();mountMotion();};preference.addEventListener?.('change',change);cleanup.push(()=>preference.removeEventListener?.('change',change));initCarousel(root,reduced);
// Static layout remains complete if a library is unavailable.
if(!g||!st||reduced)return;g.registerPlugin(st);const token=mountId;document.documentElement.classList.add('motion-ready');const fine=matchMedia('(hover: hover) and (pointer: fine)').matches;
if(window.Lenis){lenis=new window.Lenis({duration:motionSettings.scrollDuration,smoothWheel:true,syncTouch:false,prevent:node=>!!node.closest?.('dialog,.book-rail,.inside-gallery')});const tick=t=>lenis?.raf(t*1000);g.ticker.add(tick);lenis.on('scroll',st.update);cleanup.push(()=>g.ticker.remove(tick));}
listen(root,'click',e=>{const link=e.target.closest('a[href="#collection"]');const target=root.querySelector('#collection');if(link&&target){e.preventDefault();if(lenis)lenis.scrollTo(target,{offset:-80});else target.scrollIntoView({behavior:'smooth'});}});
context=g.context(()=>{
buttonLetters(root);
root.querySelectorAll('[data-split-heading]').forEach(el=>{const original=el.innerHTML;const spans=words(el);const tween=g.from(spans,{yPercent:110,rotation:5,opacity:0,duration:.85,stagger:.045,ease:'power4.out',paused:true});if(el.closest('.hero'))tween.delay(.15).play();else st.create({trigger:el,start:'top 88%',onEnter:()=>tween.play(),once:true});cleanup.push(()=>{el.innerHTML=original;el.removeAttribute('aria-label');});});
root.querySelectorAll('[data-handwriting]').forEach(el=>{g.from(el,{clipPath:'inset(0 100% 0 0)',opacity:0,duration:.9,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}});});
const hero=root.querySelector('.hero-motion');if(hero){const objects=[...hero.querySelectorAll('.book-object')];objects.forEach((obj,i)=>{const loop=g.timeline({repeat:-1,paused:true});loop.to(obj,{y:i===1?-28:22,rotationX:i===1?8:-7,rotationY:i===1?-18:16,rotationZ:i===1?6:-5,duration:motionSettings.heroCycle/2,ease:'sine.inOut'}).to(obj,{y:0,rotationX:0,rotationY:0,rotationZ:0,duration:motionSettings.heroCycle/2,ease:'sine.inOut'});st.create({trigger:hero,start:'top bottom',end:'bottom top',onToggle:self=>self.isActive?loop.play():loop.pause()});});g.from(hero.querySelectorAll('.scene-book'),{scale:.75,opacity:0,y:100,duration:1.3,stagger:.12,ease:'power3.out'});g.to(hero.querySelector('.hero-waves'),{yPercent:12,rotation:3,ease:'none',scrollTrigger:{trigger:hero,start:'top top',end:'bottom top',scrub:.7}});g.to(hero.querySelector('.hero-copy'),{y:90,ease:'none',scrollTrigger:{trigger:hero,start:'top top',end:'bottom top',scrub:1}});if(fine){const scene=hero.querySelector('.hero-scene');const x=g.quickTo(scene,'x',{duration:1.1,ease:'power3.out'}),y=g.quickTo(scene,'y',{duration:1.1,ease:'power3.out'});listen(hero,'pointermove',e=>{const r=hero.getBoundingClientRect();x((e.clientX/r.width-.5)*18);y(((e.clientY-r.top)/r.height-.5)*16);});listen(hero,'pointerleave',()=>{x(0);y(0);});}}
const showcase=root.querySelector('.book-showcase');if(showcase){g.from(showcase.querySelectorAll('.shelf-body'),{y:140,rotation:-9,opacity:0,duration:1.05,stagger:.11,ease:'elastic.out(1,0.8)',scrollTrigger:{trigger:showcase.querySelector('.book-rail'),start:'top 90%',once:true}});}
root.querySelectorAll('.shelf-body').forEach(body=>{if(!fine)return;const rx=g.quickTo(body,'rotationY',{duration:.65,ease:'power3.out'}),ry=g.quickTo(body,'rotationX',{duration:.65,ease:'power3.out'});listen(body,'pointermove',e=>{const r=body.getBoundingClientRect();rx((e.clientX-r.left)/r.width*10-5);ry(4-(e.clientY-r.top)/r.height*8);});listen(body,'pointerleave',()=>{rx(0);ry(0);});});
const fan=root.querySelector('.fan-section');if(fan){const cards=[...fan.querySelectorAll('.fan-card')];g.fromTo(cards,{x:i=>(1.5-i)*75,y:i=>95-i*20,rotation:i=>[-18,-8,4,15][i]},{x:0,y:0,rotation:i=>[-5,-7,-4,-4][i],duration:1,ease:'none',scrollTrigger:{trigger:fan,start:'top 90%',end:'center center',scrub:.75}});if(fine)cards.forEach((card,i)=>{listen(card,'pointerenter',()=>g.to(card,{y:-45,rotation:0,duration:.65,ease:'elastic.out(1,.65)',overwrite:'auto'}));listen(card,'pointerleave',()=>g.to(card,{y:0,rotation:[-5,-7,-4,-4][i],duration:.8,ease:'elastic.out(1,.65)',overwrite:'auto'}));});}
const box=root.querySelector('.unbox-scroll');if(box){const tl=g.timeline({scrollTrigger:{trigger:box,start:'top top',end:'bottom bottom',scrub:motionSettings.scrub,invalidateOnRefresh:true}});tl.fromTo('.parcel',{rotationX:50,rotationZ:-20,scale:.85,y:80},{rotationX:27,rotationZ:0,scale:1.08,y:10,duration:.3,ease:'none'},0).to('.parcel-lid',{rotationX:-120,duration:.35,ease:'none'},.08).fromTo('.unbox-note',{autoAlpha:0,y:40},{autoAlpha:1,y:0,duration:.1},.3).to('.unbox-note',{autoAlpha:0,y:-35,duration:.1},.57).to('.parcel-book-0',{x:-110,y:-110,z:160,rotationZ:-21,duration:.35},.35).to('.parcel-book-1',{x:80,y:-170,z:210,rotationZ:14,duration:.35},.4).to('.parcel-book-2',{x:160,y:-50,z:120,rotationZ:28,duration:.35},.43).to('.parcel',{scale:.66,xPercent:-30,y:100,rotationZ:-9,duration:.23},.72).fromTo('.unbox-finale',{autoAlpha:0,y:60,scale:.92},{autoAlpha:1,y:0,scale:1,duration:.15},.83).to('.unbox-progress span',{scaleX:1,duration:1,ease:'none'},0).to('.unbox-header',{opacity:0,y:-50,duration:.12},0).to('.unbox-scroll-hint',{opacity:0,duration:.1},0);}
const genres=root.querySelector('.genre-explorer');if(genres){const holders=[...genres.querySelectorAll('.genre-floater')];const show=(id)=>{genres.querySelectorAll('[data-genre-cover]').forEach(el=>el.classList.toggle('active',el.dataset.genreCover===id));g.to(holders,{scale:1,rotation:i=>[-14,13,8,-9][i],duration:.55,stagger:.025,ease:'back.out(1.7)',overwrite:true});};const hide=()=>g.to(holders,{scale:0,rotation:0,duration:.3,ease:'power2.in',overwrite:true});if(fine){genres.querySelectorAll('[data-genre]').forEach(a=>{listen(a,'pointerenter',()=>show(a.dataset.genre));listen(a,'focus',()=>show(a.dataset.genre));});listen(genres.querySelector('.genre-stage'),'pointerleave',hide);listen(genres.querySelector('.genre-stage'),'focusout',e=>{if(!genres.querySelector('.genre-stage').contains(e.relatedTarget))hide();});const movers=holders.map(el=>({x:g.quickTo(el,'x',{duration:.8,ease:'power3.out'}),y:g.quickTo(el,'y',{duration:.8,ease:'power3.out'})}));listen(genres,'pointermove',e=>{const r=genres.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;movers.forEach((m,i)=>{m.x(x*(i%2?50:-50));m.y(y*(i%2?-35:35));});});}}
root.querySelectorAll('.benefit-grid article,.gallery-grid button,.free-art').forEach((el,i)=>{g.from(el,{y:60,rotation:i%2?5:-5,opacity:0,duration:.9,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 92%',once:true}});});
const header=document.querySelector('.header');st.create({start:100,end:'max',onUpdate:self=>header.classList.toggle('scrolled',self.scroll()>100)});cleanup.push(()=>header.classList.remove('scrolled'));
},root);
Promise.resolve(document.fonts?.ready).then(()=>{if(token===mountId)st.refresh();});root.querySelectorAll('img').forEach(img=>{if(!img.complete)listen(img,'load',()=>{if(token===mountId)st.refresh();},{once:true});});
}
